Website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Contact, UserInformation, Course
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import (
    login_user,
    login_required,
    logout_user,
    current_user,
    LoginManager,
)


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        psw = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, psw):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))

            else:
                flash("Incorrect password", category="error")
        else:
            flash("User does not exist", category="error")
    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out successfully!")
    return redirect(url_for("auth.login"))


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = request.form.get("email")
        fname = request.form.get("fname")
        psw = request.form.get("password")
        cpsw = request.form.get("cpassword")
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email is alredy used", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 4 characters", category="error")
        elif len(fname) < 2:
            flash("First name must be greater than 2 characters", category="error")
        elif psw != cpsw:
            flash("The password dont match", category="error")
        elif len(psw) < 7:
            flash("Password must be at least 7 characters", category="error")
        else:
            new_user = User(
                email=email,
                First_name=fname,
                password=generate_password_hash(psw, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash("Account created!", category="success")
            return redirect(url_for("auth.login"))
    return render_template("signup.html", user=current_user)


@auth.route("/calorie")
@login_required
def calorie():
    return render_template("calorie.html", user=current_user)


@auth.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        message = request.form.get("message")
        user = User.query.filter_by(email=email).first()
        if not user:
            flash("Email not registered.", category="error")
        elif len(name) < 4:
            flash("Invalid name", category="error")
        elif len(message) < 5:
            flash("Please enter valid message", category="error")
        else:
            new_contact = Contact(Name=name, Email=email, Message=message)
            db.session.add(new_contact)
            db.session.commit()
            flash("Details Submitted", category="success")
            return redirect(url_for("views.home"))
    return render_template("contact.html", user=current_user)


@auth.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    if request.method == "POST":
        fname = request.form.get("fname")
        lname = request.form.get("lname")
        mobile = request.form.get("num")
        address = request.form.get("address")
        postcode = request.form.get("postcode")
        email = request.form.get("email")
        weight = request.form.get("weight")
        height = request.form.get("height")
        mcalories = request.form.get("mainc")
        winten = request.form.get("intensity")
        userinfor = UserInformation.query.filter_by(Email=email).first()
        userinfo = UserInformation.query.filter_by(Mobile=mobile).first()
        if len(fname) < 4 and len(lname) < 4:
            flash("Invalid name", category="error")
        elif len(mobile) < 10 and len(mobile) > 11:
            flash("Invalid Mobile Number", category="error")
        elif userinfor:
            flash("Email already registered", category="error")
        elif userinfo:
            flash("Mobile Number already used", category="error")
        else:
            new_userinfo = UserInformation(
                First_Name=fname,
                Last_Name=lname,
                Email=email,
                Mobile=mobile,
                Address=address,
                Postcode=postcode,
                Weight=weight,
                Height=height,
                M_calories=mcalories,
                Intensity=winten,
            )
            db.session.add(new_userinfo)
            db.session.commit()
            flash("Profile saved", category="success")
            return redirect(url_for("views.home"))
    return render_template("profile.html", user=current_user)

@auth.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    return render_template('dashboard.html',user=current_user)

@auth.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id):
    name_to_update=User.query.get_or_404(id)
    if request.method=="POST":
        name_to_update.First_name=request.form['name']
        name_to_update.email=request.form['email']
        try:
            db.session.commit()
            flash("User information updated successfully.", category="success")
            return redirect(url_for("auth.profile")) 
        except Exception as e:
            db.session.rollback()
            flash("An error occurred while updating user information.", category="error")

    return render_template("Update.html", user=current_user)

            
@auth.route("/delete/<int:id>", methods=["GET", "POST"])
@login_required
def delete_user(id):
    if id==current_user.id:
        user_del=User.query.get_or_404(id)
        name=None
        try:
            db.session.delete(user_del)
            db.session.commit()
            flash(("Deleted Successfully"),category='success')
        finally:
            flash("Account cannot be deleted",category="error")
            return redirect('/')
    else:
        flash("Account cannot be deletd",category="error")
        return redirect(url_for('auth.dashboard'))

@auth.route("/admin", methods=["GET", "POST"])
def admin():
    if request.method == "POST":
        username = request.form.get("email")
        password = request.form.get("password")
        if username == "Admin@34" and password == "123456789":
            return redirect(url_for("auth.adminp"))

    return render_template("admin.html")


@auth.route("/adminp")
def adminp():
    return render_template("adminp.html")


@auth.route("/Show_user")
def show_user():
    users = User.query.all()
    return render_template("user_show.html", users=users)
@auth.route("/alogout")
def admin_logout():
    logout_user()
    return redirect(url_for('auth.admin'))

# @auth.route("/Delete_user",methods=["GET","POST"])
# def delete_user(user_id):
#     user = User.query.get(user_id)
#     users=User.query.all()
#     if user:
#         db.session.delete(user)
#         db.session.commit()
#         return redirect(url_for('auth.show_user'))
#     else:
#         flash("No user with id")
    


# @auth.route("/courses", methods=["GET"])
# def courses():
#     courses = Course.query.all()
#     return render_template("view_courses.html", courses=courses)


# @auth.route("/courses/add", methods=["GET", "POST"])
# def add_course():
#     if request.method == "POST":
#         title = request.form["title"]
#         description = request.form["description"]
#         price = float(request.form["price"])

#         new_course = Course(title=title, description=description, price=price)
#         db.session.add(new_course)
#         db.session.commit()
#         flash("Course added successfully!", "success")
#         return redirect(url_for("auth.courses"))

#     return render_template("add_course.html")


# @auth.route("/courses/update/<int:course_id>", methods=["GET", "POST"])
# def update_course(course_id):
#     course = Course.query.get_or_404(course_id)

#     if request.method == "POST":
#         title = request.form["title"]
#         description = request.form["description"]
#         price = float(request.form["price"])

#         course.title = title
#         course.description = description
#         course.price = price

#         db.session.commit()
#         flash("Course updated successfully!", "success")
#         return redirect(url_for("auth.courses"))

#     return render_template("update_course.html", course=course)


# @auth.route("/courses/delete/<int:course_id>", methods=["POST"])
# def delete_course(course_id):
#     course = Course.query.get_or_404(course_id)
#     db.session.delete(course)
#     db.session.commit()
#     # flash("Course deleted successfully!", "success")
#     return redirect(url_for("auth.courses"))

Website/views.py
from flask import Blueprint,render_template,request,flash,jsonify
from flask_login import login_required,current_user
from . import db
from .models import User
import json
views=Blueprint('views',__name__)
@views.route('/',methods=["GET","POST"])
def home():
    return render_template('Main.html',user=current_user)

@views.route('/workouts')
def workout():
    return render_template('workout.html',user=current_user)

@views.route('/leftchest')
def leftchest():
    return render_template('leftchest.html', user=current_user)

@views.route('/chestBODY')
def chestBODY():
    return render_template('chestBODY.html',user=current_user)

@views.route('/chestSTR')
def chestSTR():
    return render_template('chestSTR.html' ,user=current_user)

@views.route('/shoulder')
def shoulder():
    return render_template('shoulder.html',user=current_user)

@views.route('/bicep')
def Bicep():
    return render_template('biceps.html',user=current_user)

@views.route('/forearm')
def forearm():
    return render_template('forearm.html',user=current_user)

@views.route('/abs')
def abs():
    return render_template('abs.html',user=current_user)

@views.route('/quads')
def quads():
    return render_template('quads.html',user=current_user)

@views.route('/calves')
def calves():
    return render_template('calves.html',user=current_user)

@views.route('/upperback')
def upperback():
    return render_template('upperback.html',user=current_user)

@views.route('/middleback')
def middleback():
    return render_template('middleback.html',user=current_user)

@views.route('/triceps')
def triceps():
    return render_template('triceps.html',user=current_user)

@views.route('/hamstring')
def hamstring():
    return render_template('hamstring.html',user=current_user)

@views.route('/pricing')
def pricing():
    return render_template('pricing.html',user=current_user)

Website/templates/Main.html
{% extends "index.html" %} {% block title %}Home{% endblock %}
<!DOCTYPE html>
<html lang="en">

<head>
    {%block content%}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <script defer type="text/javascript" src="{{url_for('static', filename='BMI.js')}}"></script>
</head>

<body>
    <header>
        <section class="home">
            <div class="max-width">
                <div class="home-content">
                    <h3>We'll help you reach <br>your fitness goals.</h3>
                    <button onclick="scrollWin()"class="btn">Get started</button>
                </div>
            </div>
        </section>
    </header>
    <div class="content">
        <div class="container">
            <div class="text">
                <h1>Why choose us?</h1>
                <br>
                <h3 class="secondary mb">State-of-the-Art Equipment: </h3><br>
                <p>Offer a range of modern and high-quality fitness equipment  </p>
                <h3 class="secondary mb">Expert Trainers: </h3><br>
                <p>Employ experienced and certified trainers

                </p>

            </div>
            <div class="img">
                <img src="static/img/model1.png" alt="">
            </div>
        </div>
    </div>
    <div class="trainers">
        <h2 class="primary mb">Our Professional Trainers</h2>
        <div class="trainer">

            <img src="static/img/arnold.jpg" alt="" width="400px" height="200px"/>
            <br>
            <h3 class="secondary mb">Arnold Schwarzaenegger</h3>
            <p class="tertiary mb">
                Certified trainer with an exprience of 20 years and professional <br>dietian.
            </p>

            <a href="#" class="btn-2">
                <ion-icon name="arrow-redo-circle-outline"></ion-icon>
            </a>
        </div>

        <div class="trainer">
            <img src="static/img/saket.jpg" alt="" width="350px" height="200px" />
            <h3 class="secondary mb">Saket Gokhale</h3>
            <p class="tertiary mb">
                Personalised training and variations among the exercises.
            </p>
            <a href="#" class="btn-2">
                <ion-icon name="arrow-redo-circle-outline"></ion-icon>
            </a>
        </div>
        <div class="trainer">
            <img src="static/img/cbum.jpg" alt="" width="400px" height="200px"/>
            <h3 class="secondary mb">CBUM</h3>
            <p class="tertiary mb">
                One of the best trainer that could transform your life.
            </p>

            <a href="#" class="btn-2">
                <ion-icon name="arrow-redo-circle-outline"></ion-icon>
            </a>
        </div>


    </div>
    <div class="sec">
        <div class="BMI">
            <div class="con">

                <h1>BMI Calculator</h1>

                <p>Height (in cm)</p>
                <div class="input-wrapper">
                    <input type="text" placeholder="Type here..." name="text" id="height" class="input">
                </div>
                <p>Weight (in kg)</p>
                <div class="input-wrapper">
                    <input type="text" placeholder="Type here..." name="text" id="weight" class="input">
                </div>
                <img src="static/img/BMI.png" alt="">

                <button id="btn" class="btn1">Calculate</button>

                <div id="result">

                </div>

            </div>
        </div>
    </div>
    <div class="section" id="testimonial">
        <div class="container flex">
            <div class="text">
                <h2 class="primary">
                    That's What Our Client Says
                </h2>

                <br />

                <br />
                <br />
                <div class="client">
                    <img src="https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/client1.jpg" alt="" />
                    <h2 class="secondary">Exelent Training</h2>
                    <div class="rating">
                        <input type="radio" id="star5" name="rate" value="5">
                        <label for="star5" title="text"></label>
                        <input type="radio" id="star4" name="rate" value="4">
                        <label for="star4" title="text"></label>
                        <input checked="" type="radio" id="star3" name="rate" value="3">
                        <label for="star3" title="text"></label>
                        <input type="radio" id="star2" name="rate" value="2">
                        <label for="star2" title="text"></label>
                        <input type="radio" id="star1" name="rate" value="1">
                        <label for="star1" title="text"></label>
                    </div>
                    <p class="tertiary">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi
                        quas voluptatem ad, repudiandae voluptates odio deleniti
                        reiciendis in veniam quidem expedita maxime error fugit. Pariatur
                        quasi sunt aut id. Lorem, ipsum dolor sit amet consectetur
                        adipisicing elit. Neque, officiis.
                    </p>
                </div>
                <div class="client2">
                    <img src="https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/client1.jpg" alt="" />
                    <h2 class="secondary">Exelent Training</h2>
                    <div class="rating2">
                        <input type="radio" id="star5" name="rate" value="5">
                        <label for="star5" title="text"></label>
                        <input type="radio" id="star4" name="rate" value="4">
                        <label for="star4" title="text"></label>
                        <input checked="" type="radio" id="star3" name="rate" value="3">
                        <label for="star3" title="text"></label>
                        <input type="radio" id="star2" name="rate" value="2">
                        <label for="star2" title="text"></label>
                        <input type="radio" id="star1" name="rate" value="1">
                        <label for="star1" title="text"></label>
                    </div>
                    <p class="tertiary">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi
                        quas voluptatem ad, repudiandae voluptates odio deleniti
                        reiciendis in veniam quidem expedita maxime error fugit. Pariatur
                        quasi sunt aut id. Lorem, ipsum dolor sit amet consectetur
                        adipisicing elit. Neque, officiis.
                    </p>
                </div>
            </div>
            <div class="visual">
                <!-- <img
              src="https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/testimonial.png"
              alt=""
            /> -->
            </div>
        </div>
    </div>
    <footer>
        <div class="footer-dark">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Infinity</h3>
                    <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula
                        rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel
                        in justo.</p>
                </div>
                <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i
                            class="icon ion-social-twitter"></i></a><a href="#"><i
                            class="icon ion-social-snapchat"></i></a><a href="#"><i
                            class="icon ion-social-instagram"></i></a></div>
            </div>
            <p class="copyright">Company Name © 2018</p>
        </div>
    </footer>
</div>
    {% endblock %}
</body>

</html>

Website/templates/Update.html
{%extends "index.html" %}{% block title %}Update{% endblock %}
{%block content%}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='update.css') }}">
</head>
<div class="container">
    <form method="post">

        <div class="row mb-3">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Username</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" name="email">
            </div>
        </div>
        <div class="row mb-3">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword3" name="name">
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{%endblock%}

Website/templates/calorie.html
{% extends "index.html" %} {% block title %}Calorie Calculator{% endblock %}
<!doctype html>
<html lang="en">
{%block content%}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ url_for('static', filename='calorie.css') }}">
    <link rel="stylesheet" href="style.css">

    <title>Simple Calorie Calculator using JavaScript - @code.scientist x @codingtorque</title>
</head>

<body>
    <div id="bmr-calculator" class="wrapper">
        <div class="calculator">
            <div class="choose-gender">
                <div class="segmented-control"><input id="calc-gender-male" type="radio" name="gender" value="male"
                        checked=""><label for="calc-gender-male">Male</label></div>
                <div class="segmented-control">
                    <input id="calc-gender-female" type="radio" name="gender" value="female"><label
                        for="calc-gender-female">Female</label>
                </div>
            </div>
            <label for="calc-age" id="calc-age_value">Age: 25</label>
            <input id="calc-age" type="range" value="25" min="13" max="100">
            <label for="calc-height" id="calc-height_value">Height: 180cm</label>
            <input id="calc-height" type="range" value="180" min="80" max="250">
            <label for="calc-weight" id="calc-weight_value">Weight: 80kg</label>
            <input id="calc-weight" type="range" value="80" min="40" max="200">
            <label for="calc-walking" id="calc-walking_value">Walking: 2 hours per week</label>
            <input id="calc-walking" type="range" value="2" min="0" max="50">
            <label for="calc-cardio" id="calc-cardio_value">Cardio: 1 hour per week</label>
            <input id="calc-cardio" type="range" value="1" min="0" max="50">
        </div>
        <div class="results">
            <div id="calc-target-gain">
                To Gain Weight:<br>
                <span>2700 calories</span>
            </div>
            <div id="calc-target-maintain">
                To Maintain:<br>
                <span>2400 calories</span>
            </div>
            <div id="calc-target-lose">
                To Lose Weight:<br>
                <span>1900 calories</span>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <script>
        $(".calculator input").on("input change", function (event) {
            var parameterName = $(this).attr("id").split("calc-")[1];
            var centimeters = $(this).val()

            switch (parameterName) {
                case "height":
                    $("#calc-height_value").html("Height: " + centimeters + " cm");
                    break;
                case "weight":
                    var kg = $(this).val();
                    $("#calc-weight_value").html("Weight: " + kg + " kg");
                    break;
                case "age":
                    $("#calc-age_value").html("Age: " + $(this).val());
                    break;
                case "cardio":
                    $("#calc-cardio_value").html("Cardio: " + $(this).val() + " hours per week");
                    break;
                case "walking":
                    $("#calc-walking_value").html("Walking: " + $(this).val() + " hours per week");
                    break;
            }

            var height = parseInt($("#calc-height").val(), 10);
            var age = parseInt($("#calc-age").val(), 10);
            var weight = parseInt($("#calc-weight").val(), 10);
            var walking = parseInt($("#calc-walking").val(), 10);
            var cardio = parseInt($("#calc-cardio").val(), 10);
            var gender = $(".calculator input[name='gender']:checked").val();

            // The Harris–Benedict equations revised by Mifflin and St Jeor in 1990: 'A new predictive equation for resting energy expenditure in healthy individuals'
            var bmr = parseInt(10 * weight + 6.25 * height - 5 * age, 10) + (gender === "male" ? 5 : -161);
            bmr = bmr * 1.2;
            bmr += walking * 60 * (.03 * weight * 1 / 0.45) / 7;
            bmr += cardio * 60 * (.07 * weight * 1 / 0.45) / 7;
            bmr = Math.floor(bmr);

            var targetGainWeight = Math.round((bmr + 300) / 100) * 100;
            var targetMaintain = Math.round((bmr) / 100) * 100;
            var targetLoseWeight = Math.round((bmr - 500) / 100) * 100;

            $("#calc-target-gain span").html(targetGainWeight + " calories");
            $("#calc-target-maintain span").html(targetMaintain + " calories");
            $("#calc-target-lose span").html(targetLoseWeight + " calories");
        });
    </script>
</body>
{%endblock%}
</html>

Website/templates/chestBODY.html
{% extends "index.html" %} {% block title %}Chest{% endblock %}
<!DOCTYPE html>
<html>

{%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHEST WORKOUT</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='chest.css') }}">
</head>

<body>
    <header>
        <div class="menu">
            <!-- <a href="{{url_for('views.chestBODY')}}">BODY</a>
             <button type="submit"
                onclick=url_for("chestBODY")>Body</button> -->
            <!-- <a href="{{url_for('views.leftchest)}}">Dumbell</a>
            <a href="{{url_for('views.chestSTR')}}">Streching</a>  -->
            <!-- <button type="submit"
                onclick="window.location.href= 'http://127.0.0.1:5500/chest/chestBODY.html';">Body</button>
            <button type="submit"
                onclick="window.location.href= 'http://127.0.0.1:5500/chest/chest.html';">Dumbell</button>
            <button type="submit"
                onclick="window.location.href= 'http://127.0.0.1:5500/chest/chestSTR.html';">Streaching</button> -->



        </div>
    </header>
    <h1>CHEST SECTION</h1>

    <img src="static/img/chest.jpg" alt="chess img background" class="chest">

    <div class="steps-list mb-2" style="margin: 4rem 0 1rem;">
        <video  autoplay controls loop  src="static/videos/hindu_pushups.mp4">errorrr</video>
       <div class="info">
            <li>Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.</li><br>
            <li>Lower the bar to your mid chest</li><br>
            <li>Raise the bar until you've locked your elbows.</li><br>
            <li>Lorem ipsum dolor sit amet.</li>
       </div>
    </div>

    <div class="steps-list mb-2" style="margin: 4rem 0 1rem;">
        
        <div class="info">
            <li>Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.</li><br>
            <li>Lower the bar to your mid chest</li><br>
            <li>Raise the bar until you've locked your elbows.</li><br>
            <li>Lorem ipsum dolor sit amet.</li>
        </div>
        <video autoplay controls loop src="static/videos/pushups.mp4">errorrr</video>
    </div>

    <div class="steps-list mb-2" style="margin: 4rem 0 1rem;">
        <video autoplay controls loop src="static/videos/inclinepushups.mp4">errorrr</video>
        <div class="info">
            <li>Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.</li><br>
            <li>Lower the bar to your mid chest</li><br>
            <li>Raise the bar until you've locked your elbows.</li><br>
            <li>Lorem ipsum dolor sit amet.</li>
        </div>
       
    </div>

    <div class="steps-list mb-2" style="margin: 4rem 0 1rem;">
        <div class="info">
            <li>Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.</li><br>
            <li>Lower the bar to your mid chest</li><br>
            <li>Raise the bar until you've locked your elbows.</li><br>
            <li>Lorem ipsum dolor sit amet.</li>
        </div>
        <video autoplay controls loop src="static/videos/declinepushups.mp4">errorrr</video>

    </div>

  



</body>

</html>
{%endblock%}

Website/templates/dashboard.html
{% extends "index.html" %} {% block title %}Login{% endblock %}
{% block content %}

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">

</head>

<body>
    <h2>Dashboard</h2>
    <div class="card">
        <div class="card-header">
            {{current_user.First_name}}
        </div>
        <div class="card-body">
            <h5 class="card-title">Welcome to dashboard</h5>
            <p class="card-text"><strong>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: </strong>&nbsp;{{current_user.First_name}}<br>
                <strong>Username :</strong>&nbsp;{{current_user.email}}<br>
                <strong>ID &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: </strong>{{current_user.id}}<br>
            </p>
            <a href="{{url_for('auth.logout')}}" class="btn btn-secondary">Logout</a>
            <a href="{{url_for('auth.delete_user',id=current_user.id)}}" class="btn btn-secondary">Delete Account</a>
        </div>
    </div>
   

</body>
{%endblock%}

Website/templates/delete_user.html
{% extends "index.html" %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete User</title>
</head>
<body>
    {%block container%}
    <h1>Admin Panel - User Management</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Action</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user[0] }}</td>
            <td>{{ user[1] }}</td>
            <td>
                <form action="{{ url_for('delete', user_id=user[0]) }}" method="post">
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {%endblock%}
</body>
</html>

Website/templates/rightchest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to right chest muscle</h1>
</body>
</html>